# Generated by Django 3.1.14 on 2022-01-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_name', models.CharField(max_length=50, verbose_name='사용자 이름')),
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='사용자 아이디')),
                ('password1', models.BinaryField(blank=True, max_length=200, null=True, verbose_name='사용자 비밀번호')),
                ('password2', models.BinaryField(blank=True, max_length=200, null=True, verbose_name='사용자 비밀번호(확인)')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
