<<<<<<< HEAD
# Generated by Django 3.1.14 on 2022-01-22 08:54
=======
# Generated by Django 3.1.14 on 2022-01-19 13:20
>>>>>>> 4e939d0454994fa6c1ec5fd33b562d3f9f7d3f22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='사용자 아이디')),
                ('username', models.CharField(max_length=50, verbose_name='사용자 이름')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
=======
            name='UserModel',
            fields=[
                ('user_name', models.CharField(max_length=50, verbose_name='사용자 이름')),
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='사용자 아이디')),
                ('password1', models.BinaryField(blank=True, max_length=200, null=True, verbose_name='사용자 비밀번호')),
                ('password2', models.BinaryField(blank=True, max_length=200, null=True, verbose_name='사용자 비밀번호(확인)')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일')),
            ],
            options={
                'db_table': 'User',
>>>>>>> 4e939d0454994fa6c1ec5fd33b562d3f9f7d3f22
            },
        ),
    ]
