# Generated by Django 3.1.14 on 2022-01-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_num',
            field=models.CharField(max_length=9, null=True, verbose_name='인증번호'),
        ),
    ]
