# Generated by Django 3.1.14 on 2022-01-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='사용자 비밀번호'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='사용자 비밀번호(확인)'),
        ),
    ]
