# Generated by Django 3.1.14 on 2022-05-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userauth',
            table='user_auth',
        ),
    ]
