# Generated by Django 3.1.14 on 2022-05-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220528_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='path',
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='이미지'),
        ),
    ]
