# Generated by Django 3.1.14 on 2022-02-13 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=254)),
                ('time', models.DateTimeField(auto_now_add=True, help_text='time', verbose_name='작성일')),
                ('userid', models.ForeignKey(db_column='userid', default='deleted_user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_userid', to=settings.AUTH_USER_MODEL, verbose_name='사용자 아이디')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', '초안'), ('public', '공공의')], default='draft', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='blog.user')),
            ],
        ),
    ]
