# Generated by Django 3.1.14 on 2022-05-23 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=4000, verbose_name='질문')),
                ('question_papago', models.CharField(blank=True, default=models.CharField(max_length=4000, verbose_name='질문'), max_length=4000, null=True, verbose_name='질문(papago)')),
                ('code', models.CharField(max_length=4000, verbose_name='답변')),
                ('time', models.DateTimeField(auto_now_add=True, help_text='time', verbose_name='작성일')),
                ('star', models.FloatField(blank=True, default=5.0, null=True, verbose_name='별점')),
                ('language', models.CharField(blank=True, default='Python 3', max_length=100, null=True, verbose_name='사용 언어')),
                ('preprocess', models.CharField(blank=True, default='TEST', max_length=2000, null=True, verbose_name='전저리 전 Codex 반환값')),
                ('userid', models.ForeignKey(db_column='userid', default='deleted_user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_userid', to=settings.AUTH_USER_MODEL, verbose_name='사용자 아이디')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('kid', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255, verbose_name='키워드')),
                ('qid', models.ForeignKey(db_column='qid', default='deleted_user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='keywords_qid', to='blog.user', verbose_name='질문 아이디')),
                ('userid', models.ForeignKey(db_column='userid', default='deleted_user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='keywords_userid', to=settings.AUTH_USER_MODEL, verbose_name='사용자 아이디')),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', '초안'), ('public', '공공의')], default='draft', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='blog.user')),
            ],
        ),
    ]
