# Generated by Django 3.1.14 on 2022-05-17 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='키워드')),
                ('qid', models.ForeignKey(db_column='qid', default='deleted_user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='keywords_qid', to='blog.user', verbose_name='질문 아이디')),
            ],
        ),
    ]
