# Generated by Django 3.1.14 on 2022-02-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=500, verbose_name='코드'),
        ),
        migrations.AlterField(
            model_name='user',
            name='question',
            field=models.CharField(max_length=32, verbose_name='질문'),
        ),
    ]
