# Generated by Django 3.1.14 on 2022-05-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_keywords'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keywords',
            table='keywords',
        ),
    ]
