# Generated by Django 3.1.14 on 2022-02-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220213_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=1024, verbose_name='코드'),
        ),
        migrations.AlterField(
            model_name='user',
            name='question',
            field=models.CharField(max_length=1024, verbose_name='질문'),
        ),
    ]
