# Generated by Django 3.1.14 on 2022-03-31 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20220220_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codexset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.1, max_length=10, verbose_name='코덱스온도')),
                ('userid', models.ForeignKey(db_column='userid', default='deleted_user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='codexset_userid', to=settings.AUTH_USER_MODEL, verbose_name='사용자 아이디')),
            ],
        ),
    ]
