# Generated by Django 3.1.14 on 2022-05-23 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20220517_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordCount',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255, verbose_name='키워드단어')),
                ('cnt', models.IntegerField(verbose_name='등장횟수')),
                ('qid', models.ForeignKey(db_column='qid', default='deleted_user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='keywordcount_qid', to='blog.user', verbose_name='질문 아이디')),
                ('userid', models.ForeignKey(db_column='userid', default='deleted_user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='keywordcount_userid', to=settings.AUTH_USER_MODEL, verbose_name='사용자 아이디')),
            ],
        ),
    ]
