# Generated by Django 3.1.14 on 2022-05-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_keywordcount'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keywordcount',
            table='keyword_count',
        ),
        migrations.AlterModelTable(
            name='keywords',
            table='keyword',
        ),
    ]
