# Generated by Django 3.1.14 on 2022-03-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_codexset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=4000, verbose_name='코드'),
        ),
        migrations.AlterField(
            model_name='user',
            name='question',
            field=models.CharField(max_length=4000, verbose_name='질문'),
        ),
    ]
