# Generated by Django 3.1.14 on 2022-03-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220331_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temperature',
        ),
    ]
