# Generated by Django 3.1.14 on 2022-03-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_user_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='Python 3', max_length=100, null=True, verbose_name='사용언어'),
        ),
        migrations.AddField(
            model_name='user',
            name='question_papago',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='질문(papago)'),
        ),
        migrations.AddField(
            model_name='user',
            name='star',
            field=models.FloatField(blank=True, null=True, verbose_name='별점'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=4000, verbose_name='답변'),
        ),
    ]
