# Generated by Django 3.1.14 on 2022-03-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220331_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='question_papago',
            field=models.CharField(blank=True, default=models.CharField(max_length=4000, verbose_name='질문'), max_length=4000, null=True, verbose_name='질문(papago)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='star',
            field=models.FloatField(blank=True, default=5.0, null=True, verbose_name='별점'),
        ),
    ]
